import Head from 'next/head'
import { Navbar, Sidebar } from '../ui'
import { Box } from '@mui/material'

interface Props {
  children: React.ReactNode
  title: string
}

export const Layout: React.FC<Props> = ({ children, title }) => {
  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Sidebar />
      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          flexGrow: 1,
          p: 2,
        }}
      >
        {children}
      </Box>
    </Box>
  )
}
